### ISSUE TITLE
Conflicts in environment file

### ISSUE THREAD

**Issue by Peter9192** [AI4S2S/proto#4]
The conda environment file `RGCPD_no_build.yml` pins python to 3.7.3.
The install instructions in README specifiy to install tigramite as well, but this requires python >= 3.8.

Can we bump the python version for RGCPD or loosen the constraints?

**Comment by semvijverberg** [comment]
Yes, we can. I updated the environment file.

The Python version is now fixed between 3.8 and 3.9 due to dependencies of Tigramite.  

Btw, really love mamba!
